import { AlertTriangle, BrainCircuit, CalendarDays, CheckCircle2, FileCheck2, FileText, Search, ShieldCheck, Sparkles } from 'lucide-react';

function BrowserFrame({ children, label }: { children: React.ReactNode; label: string }) {
  return <div className="overflow-hidden rounded-[28px] border border-slate-200/80 bg-white shadow-[0_30px_90px_rgba(15,23,42,.13)]">
    <div className="flex h-11 items-center gap-2 border-b border-slate-200 bg-slate-50 px-4">
      <span className="h-2.5 w-2.5 rounded-full bg-slate-300"/><span className="h-2.5 w-2.5 rounded-full bg-slate-300"/><span className="h-2.5 w-2.5 rounded-full bg-slate-300"/>
      <div className="mx-auto rounded-md border border-slate-200 bg-white px-8 py-1 text-[9px] font-medium text-slate-400">{label}</div>
    </div>{children}
  </div>;
}

export function DashboardScreen() {
  return <BrowserFrame label="app.ihalepilotu.com/dashboard"><div className="grid min-h-[430px] grid-cols-[72px_1fr] bg-[#f7f8fb] sm:grid-cols-[150px_1fr]">
    <aside className="border-r border-slate-200 bg-white p-3"><div className="h-7 rounded-lg bg-[#0b1c3d]"/><div className="mt-8 space-y-2">{[1,2,3,4,5].map(i=><div key={i} className={`h-8 rounded-lg ${i===1?'bg-blue-50':'bg-slate-50'}`}/>)}</div></aside>
    <main className="p-4 sm:p-6"><div className="rounded-[22px] bg-[#071225] p-5 text-white"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-[9px] font-semibold text-sky-200"><BrainCircuit size={11}/> Akıllı İhale Analiz Platformu</span><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_1.1fr]"><div><p className="text-2xl font-semibold tracking-tight">Şartname analizinde yeni dönem</p><p className="mt-2 max-w-md text-[11px] leading-5 text-slate-400">İhale dosyalarınızı tek panelde analiz edin ve hazırlık sürecini yönetin.</p></div><div className="grid grid-cols-2 gap-2">{['12 İhale','36 Doküman','~30 saat','82 Puan'].map(x=><div key={x} className="rounded-xl border border-white/10 bg-white/[.06] p-3 text-xs font-semibold">{x}</div>)}</div></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{['Aktif ihaleler','Yaklaşan tarihler','Son analizler'].map((x,i)=><div key={x} className="rounded-xl border border-slate-200 bg-white p-4"><div className="h-2 w-16 rounded bg-slate-200"/><p className="mt-4 text-sm font-semibold text-slate-900">{[8,3,6][i]} {x}</p><div className="mt-3 h-16 rounded-lg bg-slate-50"/></div>)}</div></main>
  </div></BrowserFrame>;
}

export function AnalysisScreen() {
  const items = [['Son teklif','24 Haziran',CalendarDays],['Geçici teminat','%3',ShieldCheck],['Zorunlu belge','12',FileCheck2]] as const;
  return <BrowserFrame label="app.ihalepilotu.com/tenders/analiz"><div className="bg-[#f7f8fb] p-5 sm:p-7"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="text-[9px] font-bold uppercase tracking-[.2em] text-blue-600">Operasyon özeti</span><h3 className="mt-2 text-xl font-semibold text-slate-950">Personel Taşıma Hizmeti Alımı</h3></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-semibold text-emerald-700">Analiz hazır</span></div><div className="mt-5 grid grid-cols-3 gap-2">{items.map(([label,value,Icon])=><div key={label} className="rounded-xl bg-slate-50 p-3"><Icon size={14} className="text-blue-600"/><p className="mt-3 text-sm font-semibold">{value}</p><p className="mt-1 text-[9px] text-slate-500">{label}</p></div>)}</div></div><div className="mt-3 grid gap-3 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2 text-sm font-semibold"><Sparkles size={15} className="text-blue-600"/> Kritik bulgular</div><div className="mt-4 space-y-2">{['TÜRSAB işletme belgesi zorunlu','D2 yetki belgesi sunulmalı','Teminat geçerlilik süresi 120 gün'].map(x=><div key={x} className="flex gap-2 rounded-lg bg-slate-50 p-3 text-[10px] text-slate-700"><CheckCircle2 size={13} className="shrink-0 text-emerald-600"/>{x}</div>)}</div></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><AlertTriangle size={17} className="text-amber-600"/><p className="mt-4 font-semibold text-amber-950">3 kritik risk</p><p className="mt-2 text-[10px] leading-5 text-amber-800">Teklif öncesi kontrol edilmesi gereken maddeler bulundu.</p></div></div></div></BrowserFrame>;
}

export function AssistantScreen() {
  return <BrowserFrame label="app.ihalepilotu.com/ihale-asistani"><div className="grid min-h-[380px] gap-0 bg-white md:grid-cols-[.8fr_1.2fr]"><div className="border-r border-slate-200 bg-slate-50 p-5"><div className="flex items-center gap-2 text-sm font-semibold"><Search size={15}/> İhale dokümanları</div><div className="mt-5 space-y-2">{['İdari Şartname.pdf','Teknik Şartname.pdf','Birim Fiyat Cetveli.xlsx'].map(x=><div key={x} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white p-3 text-[10px]"><FileText size={13} className="text-blue-600"/>{x}</div>)}</div></div><div className="p-5"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-blue-600 text-white"><BrainCircuit size={16}/></span><div><p className="text-sm font-semibold">İhale Asistanı</p><p className="text-[9px] text-slate-500">Yalnızca ihale dokümanlarınızdan yanıt verir</p></div></div><div className="mt-6 space-y-3"><div className="ml-auto max-w-[78%] rounded-2xl rounded-br-md bg-[#0b1c3d] p-3 text-[10px] leading-5 text-white">Bu ihalede sunulması gereken yetki belgeleri neler?</div><div className="max-w-[88%] rounded-2xl rounded-bl-md bg-slate-100 p-4 text-[10px] leading-5 text-slate-700">Dokümanlara göre TÜRSAB işletme belgesi ve D2 yetki belgesi sunulmalıdır. İlgili maddeleri kontrol listenize ekledim.</div></div><div className="mt-7 rounded-xl border border-slate-200 px-4 py-3 text-[10px] text-slate-400">İhale hakkında sorunuzu yazın...</div></div></div></BrowserFrame>;
}
