import { adminDb } from '@/lib/firebase/admin';
import { requireAdminPermission } from '@/lib/auth/adminGuard';
import { upsertAdminTeamMember, updateAdminTeamMember } from '../actions';
import { ShieldCheck, UserPlus, PauseCircle, PlayCircle, Trash2 } from 'lucide-react';

const ROLE_LABELS: Record<string,string> = { platform_admin:'Platform Yöneticisi', operations_admin:'Operasyon Yöneticisi', support_admin:'Destek Yöneticisi', finance_admin:'Finans Yöneticisi', content_admin:'İçerik Yöneticisi' };
export default async function Page(){
  const current = await requireAdminPermission('team');
  const [rootSnap, teamSnap] = await Promise.all([
    adminDb.collection('users').where('role','==','super_admin').get().catch(()=>null),
    adminDb.collection('users').where('role','==','admin_team').get().catch(()=>null)
  ]);
  const rows = [...(rootSnap?.docs || []), ...(teamSnap?.docs || [])].map(d=>({id:d.id,...d.data() as any}));
  return <div className="mx-auto w-full max-w-[1500px] space-y-6">
    <section className="rounded-[34px] border border-slate-200 bg-white p-8 shadow-sm"><div className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-blue-700"><ShieldCheck size={14}/>Super Admin</div><h1 className="mt-5 text-4xl font-semibold">Yönetici Ekibi</h1><p className="mt-3 text-slate-600">Platform yöneticilerini ekleyin, görev rolünü değiştirin veya erişimini kaldırın.</p></section>
    <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-semibold"><UserPlus size={18}/>Yönetici ekle</h2><form action={upsertAdminTeamMember} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input name="displayName" required placeholder="Ad soyad" className="rounded-xl border px-4 py-3"/><input name="email" type="email" required placeholder="E-posta" className="rounded-xl border px-4 py-3"/><select name="adminRole" className="rounded-xl border px-4 py-3">{Object.entries(ROLE_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input name="tempPassword" type="password" placeholder="Geçici şifre" className="rounded-xl border px-4 py-3"/><button className="rounded-xl bg-slate-950 px-4 py-3 font-semibold text-white">Ekibe ekle</button></form></section>
    <section className="overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-[.14em] text-slate-500"><tr><th className="px-6 py-4">Yönetici</th><th>E-posta</th><th>Görev rolü</th><th>Durum</th><th>Aksiyon</th></tr></thead><tbody>{rows.map((r:any)=>{const disabled=r.status==='disabled'; const self=r.id===current.session.uid; const root=r.role==='super_admin' && !r.adminRole; return <tr key={r.id} className="border-t"><td className="px-6 py-5 font-semibold">{r.displayName}</td><td>{r.email}</td><td><form action={updateAdminTeamMember} className="flex gap-2"><input type="hidden" name="uid" value={r.id}/><select name="adminRole" defaultValue={r.adminRole||'platform_admin'} className="rounded-xl border px-3 py-2" disabled={self || root}>{Object.entries(ROLE_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{!self&&!root&&<button className="rounded-xl bg-blue-50 px-3 py-2 font-semibold text-blue-700">Kaydet</button>}</form></td><td>{disabled?'Pasif':'Aktif'}</td><td>{self?<span className="text-slate-400">Mevcut hesap</span>:root?<span className="text-slate-400">Ana yönetici</span>:<div className="flex gap-2"><form action={updateAdminTeamMember}><input type="hidden" name="uid" value={r.id}/><input type="hidden" name="action" value="toggle"/><button className={`inline-flex items-center gap-2 rounded-xl px-3 py-2 font-semibold ${disabled?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{disabled?<PlayCircle size={14}/>:<PauseCircle size={14}/>} {disabled?'Aktife al':'Pasife al'}</button></form><form action={updateAdminTeamMember}><input type="hidden" name="uid" value={r.id}/><input type="hidden" name="action" value="remove"/><button className="inline-flex items-center gap-2 rounded-xl bg-rose-50 px-3 py-2 font-semibold text-rose-700"><Trash2 size={14}/>Ekipten çıkar</button></form></div>}</td></tr>})}</tbody></table></div></section>
  </div>
}
