import Link from 'next/link';
import { ArrowRight, BrainCircuit, CheckCircle2, FileSearch, ShieldCheck, Sparkles, UploadCloud } from 'lucide-react';
import { MarketingShell } from '@/components/marketing/MarketingShell';
import ProductPreview from '@/components/marketing/ProductPreview';
import { AnalysisScreen, AssistantScreen, DashboardScreen } from '@/components/marketing/ProductShowcase';

export default function HomePage(){return <MarketingShell>
<section className="relative overflow-hidden bg-[#061126] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_18%,rgba(65,123,255,.22),transparent_31%),radial-gradient(circle_at_18%_100%,rgba(14,165,233,.13),transparent_30%)]"/><div className="relative mx-auto grid max-w-[1440px] gap-14 px-5 pb-20 pt-20 lg:grid-cols-[.78fr_1.22fr] lg:items-center lg:px-10 lg:pb-28 lg:pt-28"><div><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-4 py-2 text-xs font-semibold text-sky-200"><Sparkles size={14}/> Akıllı İhale Analiz Platformu</span><h1 className="mt-7 max-w-2xl text-5xl font-semibold leading-[.98] tracking-[-.065em] sm:text-6xl xl:text-[76px]">Şartnameyi yükleyin.<br/><span className="text-sky-200">Kritik olanı görün.</span></h1><p className="mt-6 max-w-lg text-base leading-8 text-slate-300 sm:text-lg">İhale dokümanlarını analiz eder; belgeleri, tarihleri, teminatları ve riskleri tek çalışma ekranında toplar.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/iletisim" className="inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-3.5 text-sm font-bold text-slate-950 transition hover:-translate-y-0.5">Demo Talep Et <ArrowRight size={16}/></Link><Link href="#urun" className="rounded-2xl border border-white/15 bg-white/[.06] px-6 py-3.5 text-sm font-semibold">Ürünü İncele</Link></div><div className="mt-8 flex flex-wrap gap-5 text-xs text-slate-400"><span className="flex items-center gap-2"><CheckCircle2 size={14} className="text-emerald-300"/> Dakikalar içinde analiz</span><span className="flex items-center gap-2"><ShieldCheck size={14} className="text-emerald-300"/> Şirket bazlı çalışma alanı</span></div></div><ProductPreview/></div></section>

<section id="urun" className="overflow-hidden bg-white py-24 lg:py-32"><div className="mx-auto max-w-[1280px] px-5 lg:px-10"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[.22em] text-blue-600">Tek bir çalışma alanı</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.055em] text-slate-950 sm:text-6xl">İhale sürecinin tamamını görün</h2><p className="mt-5 text-base leading-8 text-slate-500">Dağınık PDF’ler, notlar ve tablolar yerine ortak ve izlenebilir bir sistem.</p></div><div className="mt-14"><DashboardScreen/></div></div></section>

<section className="bg-[#f5f7fb] py-24 lg:py-32"><div className="mx-auto grid max-w-[1280px] gap-12 px-5 lg:grid-cols-[.72fr_1.28fr] lg:items-center lg:px-10"><div><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-600 text-white"><FileSearch size={22}/></span><p className="mt-6 text-xs font-bold uppercase tracking-[.22em] text-blue-600">Doküman analizi</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.055em] text-slate-950 sm:text-5xl">Yüzlerce sayfa.<br/>Tek bakışta kritik bilgiler.</h2><p className="mt-5 max-w-md text-base leading-8 text-slate-500">Zorunlu belgeler, teminatlar, kritik tarihler ve riskler ilgili kaynaklarıyla birlikte ayrıştırılır.</p></div><AnalysisScreen/></div></section>

<section className="bg-white py-24 lg:py-32"><div className="mx-auto grid max-w-[1280px] gap-12 px-5 lg:grid-cols-[1.28fr_.72fr] lg:items-center lg:px-10"><AssistantScreen/><div className="lg:order-2"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#0b1c3d] text-white"><BrainCircuit size={22}/></span><p className="mt-6 text-xs font-bold uppercase tracking-[.22em] text-blue-600">İhale Asistanı</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.055em] text-slate-950 sm:text-5xl">Sorun.<br/>Cevabı dokümanda bulsun.</h2><p className="mt-5 max-w-md text-base leading-8 text-slate-500">Asistan yalnızca seçili ihalenin dokümanları ve analiz sonuçları üzerinden yanıt verir.</p></div></div></section>

<section id="nasil-calisir" className="border-y border-slate-200 bg-[#f8fafc] py-20"><div className="mx-auto max-w-[1100px] px-5 lg:px-10"><div className="grid gap-4 md:grid-cols-3">{[[UploadCloud,'Yükleyin','İdari ve teknik şartnameleri ekleyin.'],[BrainCircuit,'Analiz edin','Kritik bilgiler otomatik ayrıştırılsın.'],[CheckCircle2,'Yönetin','Hazırlığı ekibinizle tek yerden tamamlayın.']].map(([Icon,title,text],i)=><div key={title as string} className="rounded-[24px] border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon size={19}/></span><span className="text-xs font-bold text-slate-300">0{i+1}</span></div><h3 className="mt-6 text-lg font-semibold text-slate-950">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text as string}</p></div>)}</div></div></section>

<section className="px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1180px] overflow-hidden rounded-[36px] bg-[#071225] px-6 py-16 text-center text-white sm:px-12"><p className="text-xs font-bold uppercase tracking-[.22em] text-sky-200">İhale Pilotu</p><h2 className="mx-auto mt-4 max-w-3xl text-4xl font-semibold tracking-[-.055em] sm:text-6xl">Bir sonraki ihalenizi daha kontrollü hazırlayın.</h2><Link href="/iletisim" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-3.5 text-sm font-bold text-slate-950">Demo Talep Et <ArrowRight size={16}/></Link></div></section>
</MarketingShell>}
